env = "production"
input_directory = "vault"
output_directory = "public"
site_title = "Nver Khachoyan's Blog"
site_subtitle = "My Personal Blog - Built with Go and Obsidian Notes"
notes_per_page = 5
base_url = "/"
port = 8000
template_dir = "templates"
exclude_dirs = ["shakeit"]
landing_page = "landingPageNote"
snippets_dir = ".obsidian/snippets"

[theme]
syntax_highlighter_dark = "monokai"
syntax_highlighter_light = "github"
